# 配置URL访问路径及端口

server:
  context-path: /
  port: 8080
  
# 链接数据库
spring:
  datasource:
    type: com.alibaba.druid.pool.druidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: root    
# jsp通配符
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  
 